services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "443:443"
    depends_on:
      - web
      - api
    volumes:
      - ./lib/.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./lib/.nginx/fullchain.pem:/etc/nginx/fullchain.pem
      - ./lib/.nginx/privkey.pem:/etc/nginx/privkey.pem
  web:
    container_name: web
    build: ./web
    restart: always
    ports:
      - "3000:3000"
    command: npm start
    
  api:
    container_name: api
    build: ./api
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./api/.env
    command: npm run dev
